# Personalized Hello World Portfolio
name = "Your Name Here" # Change this!
student_id = "Your ID Here" # Change this!
course = "Game Development using Python"

print (f"Hello! I am {name}.")
print (f"Student ID: {student_id}") 
print(f"Enrolled in: {course}")

html_content= f"""
<!DOCTYPE html>
<html>
<head>
    <title>{name}'s Portfolio</title>
    <style>
        body {{font-family: Arial, sans-serif; text-align: center; margin-top: 100px; background-color: #f0f0f0; }} 
        h1 {{ color: #333; }}
        p {{font-size: 18px; }}
    </style>
</head>
<body>
<h1>Welcome to My Portfolio</h1> <p>Name: {name}</p>
<p>Student ID: {student_id}</p>
<p>Course: {course}</p>
<p>This page was generated by my Python script!</p>
</body>
</html>
"""

with open("portfolio.html", "w") as file:
    file.write(html_content)
print("HTML file 'portfolio.html' generated! Open it in a browser.")
